source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
inhibit_all_warnings!

# Pods
pod 'SimpleAuth/Instagram', :git => 'https://github.com/calebd/SimpleAuth'
pod 'SAMCache', :git => 'https://github.com/soffes/SAMCache'
pod 'SSKeychain', :git => 'https://github.com/soffes/sskeychain'
target 'SelfieBooth'