source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
inhibit_all_warnings!

# Pods
pod 'SimpleAuth/Instagram'
pod 'SAMCache'
pod 'SSKeychain'